version: "3.3"
services:
  web_scrapper:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - ./:/app
      - /Users/dlprojectsit/Library/CloudStorage/OneDrive-DLProjectsGmbH:/Users/dlprojectsit/Library/CloudStorage/OneDrive-DLProjectsGmbH
    environment:
      - APP_CLIENT_ID=0000000040172910
      - APP_CLIENT_SECRET=WAltBcwM9B3nlGDmplOUGfPLqsw5bHDA
    command: python mg_web_main.py
