version: "3.3"
services:
  airflow_web_scrapper:
    build: .
    ports:
      - "80:8080"
    # volumes:
      # - ./:/app
      # - /Users/dlprojectsit/Library/CloudStorage/OneDrive-DLProjectsGmbH:/Users/dlprojectsit/Library/CloudStorage/OneDrive-DLProjectsGmbH
    environment:
       - AIRFLOW_HOME=~/airflow
    command: airflow standalone

  airflow_excel_updater:
    build: .
    environment:
       - AIRFLOW_HOME=~/airflow
    command: airflow scheduler
